### ISSUE TITLE
Leggibilità tabelle

### ISSUE THREAD

**Issue by matteodesanti** [italia/docs-italia-theme#1]
Eliminare separatori verticali?
Eliminare sfondo alternato?

**Comment by umbros** [comment]
Ci sarebbe da aggiungere il responsive o meno delle tabelle cioè responsive o barra orizzontale?

Nel caso di responsive è necessario aggiungere alla fine (override)

.wy-table-responsive table td {
      white-space: normal !important;
   }

   .wy-table-responsive {
      overflow: visible !important;
   }

o con mediaquery

@media screen and (min-width: 767px) {

   .wy-table-responsive table td {
      white-space: normal !important;
   }

   .wy-table-responsive {
      overflow: visible !important;
   }
}

**Comment by pdavide** [comment]
Fixed in #13.
