### ISSUE TITLE
Gestione dei glossari

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#100]
Al momento il glossario deve essere incluso in un unico file. 

Questo causa dei problemi con la [Guida al linguaggio](https://docs-italia-staging.teamdigitale.it/italia/designers-italia/writing-toolkit/it/bozza/le-parole-della-pubblica-amministrazione/o.html#), dove tutte le pagine di glossario non appaiono.

Qual è il modo migliore di procedere in questo caso? Modifichiamo il documento?

**Comment by pdavide** [comment]
Se vogliamo sfruttare tutte le potenzialità del nuovo tema, la scelta è quella di modificare il documento.

**Comment by alterat** [comment]
D'accordo, allora faccio le modifiche necessarie al documento... Provo a vedere qual è la soluzione migliore. 

(Questa nel frattempo si può chiudere)
