### ISSUE TITLE
Link non funzionanti

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#105]
A volte i link esterni non funzionano, anche se formalmente corretti in RST. 

Vedi ad esempio: https://docs-italia-staging.teamdigitale.it/italia/18app/18app-esercenti-docs/it/bozza/faq-esercenti.html#non-ho-mai-emesso-fatture-elettroniche-posso-comunque-aderire-all-iniziativa-o-devo-dotarmi-necessariamente-di-alcuni-strumenti

**Comment by pdavide** [comment]
Closed via 8a2c652.
