### ISSUE TITLE
Tendina cambio versione 

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-theme#107]
Mi sembra che la tendina per il cambio della versione non funzioni correttamente, credo vada modificata aggiungendo i riferimenti a publisher e progetto corrente.

Il comportamento è visibile a questo (bellissimo) documento: https://w1.docs.iast.it/italia/designers-italia/design-docs/it/bozza/

Sono ovviamente a disposizione per test ecc.

Edit: (un altra cosa minor) per [nomi di versione lunghi](https://w1.docs.iast.it/italia/designers-italia/design-docs/it/revisione-capitolo-ui/), la tendina va a capo, è forse meglio croppare un certo numero di caratteri?

<img width="1367" alt="screen shot 2018-08-29 at 17 08 17" src="https://user-images.githubusercontent.com/481084/44796851-2a788200-abae-11e8-90a9-aa05821f6e0f.png">

**Comment by pdavide** [comment]
Rispetto all’url delle delle diverse versioni, anziché mettete una pezza nel tema, ho [aperto una PR](https://github.com/italia/docs.italia.it/pull/160) per fixare all’origine.

**Comment by pdavide** [comment]
Closed by #125
