### ISSUE TITLE
Link a tabelle e figure non allineato col testo

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#110]
I link a tabelle e figure non sono allineati con il resto del testo. Ecco un esempio:

<img width="546" alt="screen shot 2018-08-31 at 12 44 40" src="https://user-images.githubusercontent.com/19559470/44908608-587bd480-ad1c-11e8-95a9-44e5c0a593a2.png">

**Comment by pdavide** [comment]
Nice catch!
@atorin forniresti un link ad una documentazione buildata dove posso analizzare il bug?

**Comment by alterat** [comment]
Puoi prendere per esempio la Guida a Docs Italia:
- doc: https://docs-italia-staging.teamdigitale.it/italia/docs-italia/docs-italia-guide/it/bozza/index/che-cos-e-docs-italia.html#obiettivi
- repo: https://github.com/italia/docs-italia-guide/blob/master/index/che-cos-e-docs-italia.rst

**Comment by pdavide** [comment]
Closed via 65a801f.
