### ISSUE TITLE
Elenchi di secondo livello

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#112]
Gli elenchi di secondo livello (che tra l'altro sconsigliamo di usare) hanno un simbolo strano: sembra un cerchio sovrapposto a un triangolo. 

Vedi per esempio: https://docs-italia-staging.teamdigitale.it/italia/docs-italia/docs-italia-guide/it/bozza/index/che-cos-e-docs-italia.html#nuove-funzionalita

**Comment by pdavide** [comment]
Closed via 3763306.
