### ISSUE TITLE
Numerazione nelle procedure

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#113]
Riporto qui un possibile problema segnalatomi da @pablopers. 

All'interno di una procedura, la presenza di un'immagine fa ripartire la numerazione dell'elenco. È il comportamento che ci aspettiamo? 

Ecco un esempio.
Doc: https://testdig.readthedocs.io/it/latest/index/appendice-3.html#upload-tramite-interfaccia-grafica
RST: https://github.com/pablopers/docs-italia-guide/blob/master/index/appendice-3.rst

**Comment by pdavide** [comment]
L'immagine deve essere "inclusa" nel punto della lista al quale si riferisce. Tecnicamente si tratta di indentarla di 3 spazi per fare in modo che non "spezzi" la lista.
L'esempio di procedura mostrata nel demo doc presentava lo stesso problema, anche se non era visibile perché l'immagine si trova nell'ultimo punto della lista.
Closed via 723771e6c4813db2fc33855fa1f814921ca7b738.

**Comment by pdavide** [comment]
cc @pablopers

**Comment by pablopers** [comment]
Grazie Davide @pdavide. risolto e implementato cc @atorin
