### ISSUE TITLE
Documentazione 18app - Le immagini vengono distorte

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-theme#115]
Alcuni immagini sul nuovo tema vengono distorte.
È possibile confrontare le due versioni:

- https://guida-18app.readthedocs.io/it/latest/linee-guida-fatturazione.html#passo-1
- https://w1.docs.iast.it/italia/18app/18app-esercenti-docs/it/bozza/linee-guida-fatturazione.html#passo-1

Volevo chiedere come procedere. Sistemiamo i sorgenti RST del documento impostando delle dimensioni (e delle descrizioni per le figure), o è da sistemare in altro modo?

**Comment by alterat** [comment]
Vedi anche #114

**Comment by pdavide** [comment]
@francescozaia come segnala @atorin è lo stesso problema della #114 che si risolve eliminando le opzioni `:width:` e `:height:` della direttiva `figure`. Penso che il modo più semplice sia quindi sistemare i file RST.

**Comment by francescozaia** [comment]
Sono d'accordo, anche perché il tema si comporta correttamente: sono i parametri `:width:` e `:height:` di quelle immagini ad essere incorretti.
