### ISSUE TITLE
Box Devi, Dovresti e Potresti

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#116]
In alcuni documenti sono presenti i box Devi, Dovresti e Potresti, creati nel vecchio tema con delle `admonition`. 

Nel nuovo tema la vecchia sintassi sembra non funzionare (vedi qui: https://docs-italia-staging.teamdigitale.it/italia/designers-italia/lg-comunicazione-docs/it/stabile/doc/intro_linee-guida.html)

È prevista questa funzionalità nel nuovo tema? In caso negativo, come modifichiamo i vecchi documenti? Usiamo delle `admonition` normali?

**Comment by alranel** [comment]
La colorazione è molto efficace e permette documenti tecnici così formattati:
https://spid-regole-tecniche.readthedocs.io/en/latest/single-sign-on.html#authnrequest

Voto per mantenerla anche nel nuovo design, o se proprio fosse incompatibile con il suo stile valuterei ad esempio un bordo laterale colorato.

**Comment by francescozaia** [comment]
Ne abbiamo parlato anche oggi con Ale, vediamo di capire se/come dare più evidenza ai box, magari coinvolgendo anche Stefania o Daniela.
Per i box Devi, Dovresti e Potresti sfrutterei sintassi già esistenti (tipo qualcosa di simile `::warning`) e non una sintassi ad-hoc che usiamo solo noi... ma è solo un suggerimento per non over-complicare le cose.

**Comment by pdavide** [comment]
@francescozaia @alexrj questa una prima implementazione a partire dai [mockup di Docs Italia](https://projects.invisionapp.com/d/main#/console/11609034/292983273/preview).
Potrebbe andare? Avete suggerimenti?
![box_docs_italia](https://user-images.githubusercontent.com/9119858/47103554-c6824980-d23f-11e8-912f-1e0b1020a467.png)

**Comment by pdavide** [comment]
Closed via #148.
