### ISSUE TITLE
Box esempio, spazio troppo grande

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#121]
Quando viene usato un blocco di codice all'interno di un box esempio con un titolo interno, lo spazio fra questi due elementi risulta troppo grande.

Vedi ad esempio: https://testdig.readthedocs.io/it/exampledir/index/pubblicare-un-documento.html#id2

cc @pablopers

**Comment by pablopers** [comment]
il link è rotto, perché ho rimosso il repo ma controllando la guida pare risolto @atorin puoi controllare anche tu così magari @pdavide la chiude. Grazie Davide!

**Comment by alterat** [comment]
Un link equivalente è questo: https://guida-docs-italia.readthedocs.io/it/latest/index/pubblicare-un-documento.html

Mi sembra che nella maggior parte dei casi il problema sia risolto, ma non quando il linguaggio del codice è RST (vedi sezione 5.2.3). È possibile?

**Comment by pdavide** [comment]
Closed via 600af6f.
