### ISSUE TITLE
Tendina delle versioni

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-theme#131]
Ci possono essere documenti con moltissime versioni:
<img width="1440" alt="screenshot 2018-10-09 at 11 11 00" src="https://user-images.githubusercontent.com/481084/46658900-1617a400-cbb4-11e8-8349-8771e51b53bf.png">

In casi come questo, si potrebbe tamponare la cosa limitando l'altezza della tendina e aggiungendo un `overflow:scroll`.

**Comment by pdavide** [comment]
Fixed in 915d911.
