### ISSUE TITLE
Documento SPID regole tecniche: note sul nuovo tema

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-theme#144]
Ciao,
@alexrj ha fatto un veloce confronto tra l'[attuale documento su RTD](https://spid-regole-tecniche.readthedocs.io/en/latest/) e [quello su Docs Italia](https://docs.italia.it/italia/spid/spid-regole-tecniche/it/bozza/), e prima di attivare il redirect vorremmo fare un po' di modifiche al tema (o più probabilmente all'rst del documento), perché alcuni campi siano evidenziati in modo più chiaro.
In particolare:
• alcune formattazioni come i box `.. WARNING::` riconosciute da RTD non appaiono su Docs Italia
• in Docs Italia mancano alcune formattazioni cromatiche che secondo me sono piuttosto efficaci seppur graficamente invasive: con riferimento alla [pagina su RTD](https://spid-regole-tecniche2.readthedocs.io/it/latest/single-sign-on.html) e [quella su Docs Italia](https://docs.italia.it/italia/spid/spid-regole-tecniche/it/bozza/single-sign-on.html), i box SI DEVE/SI PUÒ

**Comment by pdavide** [comment]
Direttiva `.. warning::` aggiunta in 63895cb8fe88e2c3a65c83a9773a728a18e83906.

**Comment by pdavide** [comment]
cc @atorin per inserire la nuova direttiva nella guida.

**Comment by pdavide** [comment]
@alexrj @francescozaia questa una prima implementazione che ho fatto partendo dal mockup. Potrebbe andare bene?
![box_docs_italia](https://user-images.githubusercontent.com/9119858/47103339-596eb400-d23f-11e8-9aa6-87c83561b4c3.png)

**Comment by pdavide** [comment]
Chiudo per spostarci sulla #116.
