### ISSUE TITLE
Link non funzionante all'interno del box informativo

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-theme#145]
Il link presente all'interno del box mostrato di seguito non sembra essere costruito correttamente:
<img width="1409" alt="screenshot 2018-10-17 at 14 33 53" src="https://user-images.githubusercontent.com/481084/47096916-810a5000-d230-11e8-8659-eafecc92af95.png">

**Comment by pdavide** [comment]
Closed via 2cb98e9.
