### ISSUE TITLE
Integrazione Forum: piccoli bug di front-end quando ci sono più topic nella stessa pagina

### ISSUE THREAD

**Issue by pdavide** [italia/docs-italia-theme#150]
Nel secondo thread di commenti visualizzato:
- Lo stile dei box per l'inserimento dei commenti salta (inclusi altri elementi correlati attorno al box)
- Il bottone +/- per espandere il thread di commenti causa l'espansione/collasso di tutti i thread presenti nella pagina
- Il secondo thread mostra il link "Logout" anche se non è stato fatto il login
- Dopo il login, facendo un espandi/collassa dei thread, sopra il box del primo thread appare `Contenuto è troppo corto (il minimo è di 20 caratteri)<br>Contenuto sembra poco chiaro, è una frase completa?`
- Dopo il login, non è possibile inserire commenti nel box del secondo thread

In generale proporrei di tenere due thread nel documento demo in modo da evitare regressioni non visibili con la presenza di un solo thread.

**Comment by ninomarrazzo** [comment]
Risolve la seguente PR: https://github.com/italia/docs-italia-theme/pull/153.
Grazie
