### ISSUE TITLE
Glossario non visibile

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-theme#155]
Per il documento LG comunicazione, il [glossario su Docs Italia](https://docs.italia.it/italia/designers-italia/lg-comunicazione-docs/it/bozza/doc/glossario.html) risulta vuoto, mente in realtà contiene delle voci nella [versione RTD](https://comunica-lg.readthedocs.io/it/latest/doc/glossario.html).

Presumo si tratti di com'è scritto l'`.rst` di quella pagina, ma andrebbe visto prima di creare il redirect.

**Comment by pdavide** [comment]
Fixed via 7d6c80741aa6a3b5b00440307db661be47847dc9.
Bonus => https://github.com/italia/lg-comunicazione-docs/pull/8 cc @francescozaia
