### ISSUE TITLE
Nota dentro una tabella

### ISSUE THREAD

**Issue by peterampazzo** [italia/docs-italia-theme#157]
In riferimento alla nota presente nella pagina: https://docs-italia-staging.teamdigitale.it/comunedipadova/mobilita-data/mobilita-data/it/master/_docs/comunedipadova.html - ho notato che la nota non compare dopo il click sul pulsante, ma il contenuto è presente nel sorgente della pagina.

Comunque tempo funzionava tutto e compariva - con un click - simile ad una tooltip e non come avviene ora in queste note: https://docs-italia-staging.teamdigitale.it/citta-metropolitana-amba-raba/popolazione/altra-anagrafe-docs/it/bozza/index.html.

**Comment by pdavide** [comment]
Fixed via 60a23ec7.

**Comment by pdavide** [comment]
Grazie per la segnalazione @peterampazzo!
