### ISSUE TITLE
Pulsante Mostra tutto in box Approfondimento

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#163]
In alcuni casi i box di Approfondimento mostrano già tutto il contenuto presente, senza dover cliccare sul pulsante Mostra tutto. In questi casi, la voce Mostra tutto è superflua e potrebbe essere eliminata.

**Comment by pdavide** [comment]
Fixed via a84e16255e05decd0ce6e5a8a150d14f51361436.
