### ISSUE TITLE
La funzionalità "copia link" non funziona su FF

### ISSUE THREAD

**Issue by pdavide** [italia/docs-italia-theme#166]
Bug confermato su OS linux (debian) e mac.

**Comment by francescozaia** [comment]
Sembrano semplicemente mancare i parametri `event` alle funzioni `copyNav`, `copyGlossaryLink` e forse altre (da controllare).

**Comment by pdavide** [comment]
Fixed via 84cdcf788f7a57ad28f74fc40cf104f6628f70cf.
Thanks @francescozaia!
