### ISSUE TITLE
link in footer 404

### ISSUE THREAD

**Issue by mfortini** [italia/docs-italia-theme#196]
Nei footer delle pagine interne, es
https://docs.italia.it/italia/developers-italia/lg-acquisizione-e-riuso-software-per-pa-docs/it/stabile/attachments/allegato-c-guida-alle-licenze-open-source.html

i link "Cookie policy" e "Note legali" mancano del / finale e risultano in un 404

**Comment by bfabio** [comment]
Fixed in #218.
