### ISSUE TITLE
comportamento menù/indice

### ISSUE THREAD

**Issue by sbronzolo** [italia/docs-italia-theme#23]
Usando la documentazione ho incontrando un problema che è particolarmente fastidioso soprattutto quando consulti velocemente il documento passando da un paragrafo all’altro. 
Quando clicchi su un paragrafo, il menù di sinistra correttamente apre l’accordion in cui quel paragrafo è contenuto (il blocco diventa grigio). Ma non riposiziona il menù portando quel blocco grigio in alto. Il risultato è che la posizione del blocco grigio è variabile (te lo puoi trovare in alto o in basso) e addirittura potresti non vederla, se il menù è molto lungo potresti dover usare la barra di scorrimento per vederla 
Qui l’esempio
http://design-italia.readthedocs.io/it/stable/doc/service-design/accessibilita.html#un-esempio-per-capire-uso-del-colore
Forse nel nuovo tema il comportamento è un po' diverso ma lo stesso problema si ripresenta
http://cloud-pa.readthedocs.io/it/latest/circolari/SaaS/circolare_docs/articolo-7.html
Credo che un comportamento corretto sarebbe posizionare il blocco grigio in alto, lasciando intravere una riga del menù nero sopra per far capire che il menù continua sopra più o meno così
<img width="1440" alt="schermata 2018-02-16 alle 09 56 19" src="https://user-images.githubusercontent.com/24827270/36299989-ad23b212-12ff-11e8-8290-8f03e54d7a4b.png">

**Comment by francescozaia** [comment]
Ne abbiamo discusso anche con @pdavide, e confermiamo la necessità del fix.

Essendo una issue già presente sull'attuale tema, presumo non sia indispensabile per la messa online della prima release "statica". Ad ogni modo, sarà presa in carico al più presto.

**Comment by pdavide** [comment]
Un altro problema simile a quello segnalato in questa issue si presenta quando la pagina è particolarmente lunga ed il menu assume la stessa lunghezza della pagina. Il tema precedente rendeva "sticky" la sidebar che non scrollava più mentre la pagina continuava. Non so quale fosse l'implementazione del tema precedente, qui comunque un riferimento ad una libreria js adatta allo scopo: https://abouolia.github.io/sticky-sidebar/

**Comment by gunzip** [comment]
se avete usato il Tk considera che include https://popper.js.org/ con cui forse è possibile ottenere lo stesso effetto (tra l'altro è incluso anche in bootstrap4 : )

btw, l'implementazione del vecchio tema è terribile perché tiene male in sync lo scroll della sidebar che scrolla a una velocità diversa di quella del main div (l'effetto è visibile qui https://design-italia.readthedocs.io/it/stable/)
