### ISSUE TITLE
Leggibilità font bold 

### ISSUE THREAD

**Issue by roby986** [italia/docs-italia-theme#24]
Con il nuovo tema ho riscontrato, in alcuni casi, un problema di leggibilità del font in bold (nello screen ad esempio vedi "Top motori di ricerca referenti" e altri titoletti a seguire).

 
![font_web analytics](https://user-images.githubusercontent.com/29751207/36315441-083db94e-1338-11e8-8eeb-3aece438f17c.png)

**Comment by pdavide** [comment]
Resolved in #27
