### ISSUE TITLE
Altezza fissa del link alle versioni statiche del testo

### ISSUE THREAD

**Issue by gunzip** [italia/docs-italia-theme#26]
propongo di levare 100px di altezza all'elemento fixed della navbar che attualmente occupa più spazio di quel che potrebbe:

https://github.com/italia/docs-italia-theme/blob/b26ac5a60208e601bacb446e5a2ba9c0fedbec17/sass/badge_only.sass#L96

![image](https://user-images.githubusercontent.com/148224/36340794-fa08a5d0-13e3-11e8-8f65-4f9e37753996.png)

**Comment by pdavide** [comment]
La rimozione dell'altezza fissa causa uno "sfarfallamento" durante lo scroll nella zona footer.
Lo spazio che attualmente sembra vuoto sarà occupato dall'elenco delle versioni del documento disponibili.
La issue resta comunque aperta perché il bug necessita qualche approfondimento.

**Comment by pdavide** [comment]
Fixed in #37
