### ISSUE TITLE
Formattazione admonitions

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#32]
- I riquadri di _admonition_ predefiniti si estendono oltre il corpo del testo. La barra del titolo non ha la stessa larghezza del resto del riquadro. È il comportamento previsto?

- I riquadri di _admonition_ personalizzati (quelli ottenuti con `.. admonition:: <Nome admonition>` ) hanno un rientro diverso rispetto al resto del testo. 

Esempio: http://admo.readthedocs.io/

**Comment by pdavide** [comment]
Ciao @atorin ho fixato il primo punto nella #33.
Rispetto al secondo non so se la feature delle admonitions generiche era stilizzata nel tema sphinx_rtd, necessita di un ulteriore approfondimento. Nelle documentazioni di Docs Italia, ti risulta che siano utilizzare admonitions generiche da qualche parte?

**Comment by alterat** [comment]
Ciao @pdavide! Grazie per le modifiche.
Riguardo alle _admonition_ generiche, al momento credo che nessun documento le utilizzi. 
Avevo provato a usarle per dei casi particolari (un box di Casi di studio) ma ho desistito per via del bug. 
Non è una feature di alta priorità però.
