### ISSUE TITLE
Riquadri di admonition personalizzati

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#34]
I riquadri di _admonition_ personalizzati (quelli ottenuti con .. admonition:: <Nome admonition> ) hanno un rientro diverso rispetto al resto del testo.

Comportamento suggerito: dovrebbero avere rientri e larghezza uguali a quelli dei box predefiniti. 

Esempio: http://admo.readthedocs.io/it/latest/

Vedi anche: #32

**Comment by francescozaia** [comment]
Sistemato nel branch [images-and-logos](https://github.com/italia/docs-italia-theme/tree/images-and-logos)
