### ISSUE TITLE
Gestione dei documenti multilingua

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#40]
Al momento, sembra che non ci sia un pulsante per cambiare la lingua di un documento. 

Esempio.
ITA: http://admo.readthedocs.io/it/latest/
ENG: http://admo.readthedocs.io/en/latest/

**Comment by pdavide** [comment]
Ho approfondito la questione e non ho trovato alcun modo per rilevare automaticamente se esistono versioni tradotte di un documento.
RTD non espone l’informazione in alcuna variabile disponibile a sphinx, e neanche via API.
Ritengo che l’unico modo sia esplicitare l’esistenza di una versione tradotta nel `conf.py`.

**Comment by alterat** [comment]
L'alternativa offerta da RTD è specificare la traduzione nella scheda Translations: http://docs.readthedocs.io/en/latest/localization.html

Il problema è che al momento il tema non mostra la possibilità di scegliere una lingua, come invece accadeva con la versione precedente (vedi https://pianotriennale-ict.readthedocs.io/it/latest/). È possibile ripristinare quella funzionalità?

**Comment by pdavide** [comment]
@atorin il mio commento era proprio relativo alla funzionalità offerta da RTD che hai linkato.
Nel tema di default RTD inietta i link alle versioni in altre lingue.
Con il nostro tema non è possibile esporre automaticamente gli stessi link se non esplicitando l’esistenza di versioni in altre lingue (impostate su RTD) nel `conf.py`.

**Comment by alterat** [comment]
Ah d'accordo! Scusami, non avevo capito, pensavo fosse semplicemente un problema di "pulsanti mancanti".

Aggiungere una riga nel conf.py mi sembra un approccio abbastanza ragionevole, se questo aiuta a risolvere il problema.
