### ISSUE TITLE
Nuove versioni del tema per i documenti versionati

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#41]
Al momento, la raccomandazione è di inserire `git+https://github.com/italia/docs-italia-theme@v1.0-beta` nel file _requirements.txt_. 

Cosa succede ai documenti versionati con tag quando il tema cambierà versione? Mi riferisco, per esempio, al CAD: cad.readthedocs.io.

Lo scenario è questo:
1. Creo il doc. Il requirements specifica la versione del tema 1.0beta;
2. Modifico il doc e taggo la versione 1.0;
3. Modifico il doc e taggo la versione 2.0;
4. Modifico il file requirements con il tema alla versione 1.0 release.

Quando arrivo a 4., che tema userà la documentazione? Non userà il file requirements del punto 1., e quindi il vecchio tema? Per cambiare il tema a **tutte le versioni** sarei costretto a fare un rebase, coi problemi che questo comporta per i tag.

Che ne pensate, @pdavide e @francescozaia ?

**Comment by pdavide** [comment]
@atorin vedo due possibili soluzioni:
- manteniamo il modello attuale senza la necessità di “riportare” nuove releases del tema su vecchie versioni dei documenti (considerato anche che nuove release potrebbero richiedere modifiche al conf.py)
- non usiamo il sistema dei tag per il tema, ma quello dei branch, in modo da non legarci alla commit history e avere l’ultima versione sempre disponibile su uno specifico branch (“stable” ad esempio).
@francescozaia tu che ne pensi?

**Comment by francescozaia** [comment]
Io propenderei per il punto 1 indicato da @pdavide, perché il versionamento del tema (e quindi l'utilizzo dei tag) è, a mio avviso, imprescindibile.
L'unico "contro" è ovviamente il fatto che la _versione del tema applicato_ è legata a doppio filo con la _versione della documentazione_, ma non lo vedo come un problema particolarmente grave.

Possiamo farci due parole anche con @xrmx quando ci sentiamo, vista la sua maggior esperienza con la gestione di dipendenze.

**Comment by alterat** [comment]
@francescozaia 
Il problema di legare la versione della documentazione a quella del tema è che a ogni nuova versione del tema dovresti aggiornare la versione dei documenti, andando a modificare il file _requirements_. Questo non è possibile per documenti come il CAD.

Viceversa, la seconda proposta di @pdavide, cioè usare un branch stable per i documenti, permetterebbe di non modificare il _requirements_. L'ggiornamento del tema della documentazione si ottiene con un semplice rebuild in RTD. Credo che i tag siano compatibili con questa soluzione: ogni documento avrebbe sempre il tema associato al tag più recente.

**Comment by francescozaia** [comment]
Capisco la problematica di versione per documenti che hanno necessità di versionamento così stringente.

Si potrebbe anche lasciare il _requirements.txt_ senza alcuna indicazione di tag/branch, così che possa sfruttare semplicemente il branch `master` del tema come sorgente.

**Comment by alterat** [comment]
@francescozaia 
La soluzione che proponi sarebbe l'ideale. In questo modo, una volta aggiunto il file _requirements.txt_, chi pubblica la documentazione si può quasi dimenticare del tema, che viene gestito separatamente. 

Con questo approccio, il branch `master` dovrebbe sempre avere l'ultima versione funzionante disponibile (quella con il tag).

Ci sono problemi a usare questo approccio sin da ora secondo te?

**Comment by alterat** [comment]
Non credo che degli aggiornamenti al tema possano impedire la corretta compilazione dei documenti. 

Secondo me questo è il tipico caso in cui il contenuto della pagina è separato dall'aspetto grafico. Credo che sia importante che i documenti su Docs Italia abbiano sempre l'ultima versione del tema, per incorporare gli ultimi miglioramenti (come, per esempio, il nuovo switch per la lingua, implementato di recente). 

L'aspetto di riproducibilità riguarda soprattutto il contenuto, a mio avviso. In altri termini, il documento rimane lo stesso se il contenuto è lo stesso, anche se ci sono piccole differenze nel tema.

**Comment by pdavide** [comment]
Mi sembra che la soluzione identificata sia quella di non inserire il tag nella dipendenza dal tema specificata nel file `requirements.txt`.
@atorin possiamo documentare questa decisione e chiudere la issue?

**Comment by alterat** [comment]
Qual è il modo migliore per documentare la decisione? Non credo che sia il caso di farlo a livello di "Guida a Docs Italia", essendo un problema puramente del tema di stile. 

Potremmo aggiungere qualcosa nel README a questo repo? Ha senso?

**Comment by pdavide** [comment]
Andrebbe documentato lì dove diamo le istruzioni per compilare il file `requirements.txt`.

**Comment by alterat** [comment]
OK, lo posso aggiungere lì. 

L'unico svantaggio è che questa informazione non è di utilità per gli utenti (che usano il `requirements.txt` già pronto), ma sarebbe più che altro una nota per noi. 

Però non vedo molte alternative, quindi farò come suggerisci.
