### ISSUE TITLE
Revisione grafica degli spazi

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-theme#47]
Ho ricevuto da più parti lamentele sul fatto che il nuovo tema abbia una distribuzione degli spazi migliorabile. Mi segnalano in particolare:

* a sinistra nel menu c'è troppo spazio sprecato
* nella parte a destra del testo, c'è molto spazio vuoto
* inoltre non vengono renderizzati bene i blocchi di codice (nel senso che il css utilizzato non è molto chiaro nel distinguere codice dal testo)

Provo a fare un passaggio a voce con @matteodesanti, nel caso commento in seguito.

**Comment by pdavide** [comment]
Il problema è tanto più evidente quanto più ci si avvicina al breakpoint di 1366px partendo da larghezze maggiori. Forse un primo intervento potrebbe essere nella direzione di fissare un breakpoint ad una larghezza maggiore per la visualizzazione dei margini laterali.

**Comment by francescozaia** [comment]
C'è una prima prova su https://github.com/italia/docs-italia-theme/tree/layout-rework
