### ISSUE TITLE
Loghi a fondo pagina

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#59]
Il logo di AgID in calce sembra più grande e leggermente più in basso rispetto a quello del Team Digitale. Dovrebbero forse avere la stessa grandezza ed essere allineati?

**Comment by francescozaia** [comment]
+1, inoltre andrebbe aggiornato il logo AGID al nuovo (visibile su https://ia.italia.it/ e che ho in formato svg, nel caso servisse) e rimosso l'emblema della Repubblica dal logo del TD.

**Comment by pdavide** [comment]
@francescozaia come mai dici di rimuovere lo stellone accanto al logo del TD? È presente in tutti i siti.

**Comment by francescozaia** [comment]
@pdavide hai ragione, errore mio che facevo riferimento all'unico posto dove non c'è: il [footer del sito del team](https://teamdigitale.governo.it/#footer) 😅

**Comment by pdavide** [comment]
Ho sistemato il footer di https://docs.italia.it.
@francescozaia sistemo anche quello del tema nel branch della tua PR?
