### ISSUE TITLE
Introdurre meccanismo di prevenzione caching CSS

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-theme#61]
Abbiamo ricevuto segnalazione di layout visualizzati male, molto probabilmente a causa di cache persistente sui file CSS.

Introdurre un meccanismo che preveda l'utilizzo di nomi di file diversi, querystring o simile per gli asset che possano essere affetti da tale problema (JS e CSS in primis).

**Comment by pdavide** [comment]
Risolto in 4948965f1122e45210fa7d5216bce738986d6b09.
