### ISSUE TITLE
Indicare un codice della versione anche per quella "latest"

### ISSUE THREAD

**Issue by ggentili** [italia/docs-italia-theme#65]
Se si guarda un documento pubblicato come...
http://design-italia.readthedocs.io/it/latest/doc/introduzione-linee-guida-design.html
...se uno vuole citare una delle versioni precedenti può facilmente usare i codici 2018.1 e 2017.1
ma se uno volesse citare la versione corrente come fa? La definisce "latest al 10/05/2018"?
Potrebbe esserci un codice facilmente visibile per tutti, magari diverso
dalla codifica usate per le release di tipo "stable"?

**Comment by pdavide** [comment]
Ciao @ggentili,
innanzitutto grazie per la issue, intercetta uno use case che non avevamo considerato. Per questo ti chiedo qualche chiarimento per capire meglio.
La versione *corrente* è la `stable`, non la `latest`, che invece è una versione in lavorazione, come puoi leggere anche [qui](http://design-italia.readthedocs.io/it/stable/doc/introduzione-linee-guida-design.html#version-control-e-release-della-documentazione).
Certamente è molto importante poter fare una citazione dalla versione `stable`, ma qual è l'esigenza di citare qualcosa da una versione in lavorazione che potrebbe cambiare senza preavviso? Se si tratta di una proposta di modifica, o segnalazione di un errore, allora è meglio usare GitHub (linkato dal bottone in alto a dx nei documenti) per fare una proposta/richiesta puntuale su file o singole linee di codice. Tu quale caso d'uso immaginavi?

**Comment by ggentili** [comment]
nel link che citi la versione "stable" viene associata al termine "ufficiale" e mi sembra giusto che sia proprio la versione formalmente approvata ovvero (per usare proprio il burocratese) la versione "vigente".

a mio avviso si può dire che la versione "latest" sia quella corrente, quella ad oggi più fresca, ma non è quella approvata ufficialmente e vigente (che è la "stable").

il termine "latest" fa chiaramente pensare all'ultimo rilascio/release, anche se non stable.
siccome sono termini del mondo software bisogna adattarli alle PA in modo che non creino confusione.

per questo suggerivo che quando si scegli di vedere la versione "latest" dovrebbe comparire vicino al selettore o con una barra molto evidente in zona header, che si tratta di una versione in via di elaborazione ed ancora non approvata ufficialmente.

inoltre, se si aggiungesse anche un codice tipo "2018.2.beta" oppure "latest al 10/05/2018" si permetterebbe alle persone delle PA di far riferimento a capitoli della versione in elaborazione inserendo negli atti una citazione chiara a tutti ed uniforme. altrimenti si possono citare solo le versioni stable.

**Comment by pdavide** [comment]
@ggentili accolgo la tua osservazione che avevamo già inserito nella nostra [roadmap pubblica](https://trello.com/b/jQUgRzRe/docs-italiasviluppo) in [questa card](https://trello.com/c/AGOhU8q8).
L'etichetta `latest` non sembra adatta e sarà quindi modificata. Probabilmente inseriremo anche un avviso quando l'utente sta visualizzando la versione `latest`/`bozza`, come tu proponi.

Rispetto alla tua ultima proposta, non sono molto convinto rispetto al caso d'uso che vede un funzionario della PA citare, in un atto, un brano/capitolo di un documento in lavorazione. Il riferimento per la PA è la versione `stable`. La versione `latest` è resa pubblica per finalità di sviluppo collaborativo. Resta sempre la possibilità di fare riferimenti puntuali usando GitHub.
