### ISSUE TITLE
conf.py snippet is not enough to use this theme

### ISSUE THREAD

**Issue by alranel** [italia/docs-italia-theme#8]
README instructs users to add the following lines to the project's conf.py:

```ruby
import sphinx_rtd_theme
html_theme = "sphinx_rtd_theme"
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
```

However this only applies to local builds, while RTD builds lack the `<link>` tags for the theme stylesheets. It looks like the following code is needed as well (see the [design-doc conf.py](https://github.com/italia/design-doc/blob/238ff56d7186a0a32431780e8ed8110c2855c69c/conf.py#L84-L94)):

```ruby
if not on_rtd:  # only import and set the theme if we're building docs locally
    html_theme = 'sphinx_italia_theme'
    html_theme_path = ["_themes", ]
else:
    # Override default css to get a larger width for ReadTheDoc build
    html_context = {
        'css_files': [
            '_static/css/theme.css',
            '_static/css/custom.css',
        ],
    }
```

A sample conf.py should be included in this repository (like in the newer https://github.com/italia/docs-italia-theme) and/or the README should be updated.

**Comment by pdavide** [comment]
Closing as superseeded by new docs-italia-theme
