### ISSUE TITLE
Parametro collapse_navigation

### ISSUE THREAD

**Issue by alterat** [italia/docs-italia-theme#99]
Vogliamo mettere questo parametro di default nel nuovo tema?

**Comment by pdavide** [comment]
Il parametro `collapse_navigation` non ha alcun effetto sul layout del nuovo tema. Se vogliamo modificare il layout della navigazione possiamo aprire una issue apposita per discutere su come intendiamo impostarla.

**Comment by alterat** [comment]
OK, grazie per il chiarimento. In fondo non è un problema prioritario, quindi possiamo ridiscuterne più avanti, quando sperimentiamo come funziona la navigazione sui vari documenti.
